import type { AccessPoint, ArrivalLayoutKind } from '@/entities/tenant';

export function uniqueFloorIds(floorIds: readonly string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const raw of floorIds) {
    const id = raw.trim();
    if (!id || seen.has(id)) continue;
    seen.add(id);
    result.push(id);
  }
  return result;
}

/** UI + id rules: single list from forFloors and legacy alsoForFloors. */
export function mergeAccessPointDisplayFloors(point: AccessPoint): string[] {
  return uniqueFloorIds([...(point.forFloors ?? []), ...(point.alsoForFloors ?? [])]);
}

const FLOOR_ID_SLUG = /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/;

export function isValidStayFloorIdForAccessPointId(floorId: string): boolean {
  return FLOOR_ID_SLUG.test(floorId.trim());
}

export function isAutoGeneratedAccessPointId(id: string): boolean {
  if (id === 'building_entrance') return true;
  if (/^outside_\d+$/.test(id)) return true;
  if (/^zone_\d+$/.test(id)) return true;
  return false;
}

function isEmptyPointDefaultId(id: string, index: number): boolean {
  return id === `floor_${index}`;
}

function shouldReplaceAccessPointId(
  id: string,
  index: number,
  stablePointIds: ReadonlySet<string>
): boolean {
  if (!id.trim()) return true;
  if (stablePointIds.has(id)) return false;
  if (isEmptyPointDefaultId(id, index)) return true;
  if (isAutoGeneratedAccessPointId(id)) return true;
  if (/^floor_[a-zA-Z0-9_-]+$/.test(id)) return true;
  return false;
}

function resolveOutsideAccessPointId(
  point: AccessPoint,
  index: number,
  layoutKind: ArrivalLayoutKind,
  points: AccessPoint[]
): string {
  const outsidePoints = points.filter((item) => (item.kind ?? 'zone') === 'outside');
  const isOnlyOutside = outsidePoints.length === 1 && outsidePoints[0] === point;

  if (
    layoutKind === 'building_then_zones' &&
    (index === 0 || isOnlyOutside)
  ) {
    return 'building_entrance';
  }

  return `outside_${index}`;
}

export function proposeAccessPointId(
  point: AccessPoint,
  index: number,
  layoutKind: ArrivalLayoutKind,
  points: AccessPoint[]
): string {
  const kind = point.kind ?? 'zone';

  if (kind === 'outside') {
    return resolveOutsideAccessPointId(point, index, layoutKind, points);
  }

  const floorIds = mergeAccessPointDisplayFloors(point);
  if (floorIds.length === 1 && isValidStayFloorIdForAccessPointId(floorIds[0])) {
    return `floor_${floorIds[0]}`;
  }

  return `zone_${index}`;
}

/**
 * Assigns sortOrder and stable ids for draft/save. Preserves ids loaded from tenant settings.
 */
export function ensureAccessPointIds(
  points: AccessPoint[],
  layoutKind: ArrivalLayoutKind,
  stablePointIds: ReadonlySet<string> = new Set()
): AccessPoint[] {
  return points.map((point, index) => {
    const sortOrder = index;
    const currentId = point.id?.trim() ?? '';
    const nextId = shouldReplaceAccessPointId(currentId, index, stablePointIds)
      ? proposeAccessPointId(point, index, layoutKind, points)
      : currentId;

    return {
      ...point,
      id: nextId,
      sortOrder,
    };
  });
}
